# Group Sessions

## Session [/sessions]

### End Customer session [DELETE]

+ Request (application/json)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832
            clientId: adsaf2321224123

+ Response 204

    + Header

            Location: session/
            Expires: Sun, 08 Nov 2015 21:11:41Z
            Last-Modified: Thu, 04 Jun 2015 21:11:41Z
            Cache-Control: private
