# Data Structures

## Pocket Overview (object)
+ id: eur_realmoney (string, required) - The pocket unique identifier
+ pocket_groups: G1, G2 (array, optional) - The Pocket groups the pocket belongs to
+ name: Euro pocket (string, optional) - The user friendly name of the pocket
+ balance (Balance)
+ details: /wallets/johnswallet/pockets/euro_pocket (string, required) - The relative link to the pocket details

## Pocket Detail (Pocket Overview)
+ type: realmoney (string, required) - The type of the pocket
+ transactions: /wallets/johnswallet/pockets/euro_pocket/transactions" (string, required) - The relative link to the pocket transactions

## Balance (object)
+ amount: 120.00 (number, required) - The wallets total balance by currency
+ currency (object)
    + name: Euro (string, required) - The user friendly name of the currency
    + symbol: € (string, optional) - Optional currency symbol
    + iso_code: EUR (string, required) - The ISO 4217 currency code

## Wallet (object)
+ total_balance (array[Balance], required)
+ transactions: wallets/johnswallet/transactions (string, required) - The relative url to the wallet history
+ debit: wallets/johnswallet/debit (string, required) - The relative url used to debit the current wallet
+ credit: wallets/johnswallet/credit (string, required) - The relative url used to credit the current wallet
+ startdebit: wallets/johnswallet/startdebit (string, required) - The relative url used to start a asyncronous debit on the current wallet
+ startcredit: wallets/johnswallet/startcredit (string, required) - The relative url used to start a asyncronous debit on the current wallet
+ pockets (array[Pocket Overview], required)

## Async Transaction Response (object)
+ transaction_id: sdkjfbsidf123123 (string, required) - The transaction id for the completted transaction
+ expires_at: `016-02-10T14:31:12Z` (string, required) - The time untill the transaction is keept open

## Transaction Response (object)
+ successfull: true (boolean, required) - Determines if the request was Successfull
+ affected_pockets (array[Pocket Overview])
+ balances (array[Balance])
+ transaction_id: sdkjfbsidf123123 (string, required) - The transaction id for the completted transaction
+ details: /wallets/johnswallet/transactions/sdkjfbsidf123123 (string, required) - The relative URL to the transaction details for this operation

## Transaction Detail (object)
+ timestamp: `2016-02-12T13:43:22Z` (string, required) - The timestamp of the transaction in UTC
+ status: Completed (string, required) - The status of the transaction. Values are [Completed, Pending, Canceled, Storno]
+ transaction_id: sdkjfbsidf123123 (string, required) - The unique transaction id
+ type: payin (string, required) - The transaction type
+ ammount (Balance)
+ tags: payin, customer (array, required) - The associated tags for this transaction

## Transaction Request (object)
+ amount: 20.00 (number, required) - The ammount that the wallet should be changed by
+ pocket: euro_pocket (string, required) - Identifies the pocket affected by the transaction
+ tags: payin, customer (array, required) - The associated tags for this transaction
