# Group Wallets

Defines access methods for wallet functionality.


## Wallet [/wallets/{user_identifier}]

Required access grants

| HTTP verb | Grant|
| :--- | :--- |
| GET | get_user_wallet |
| POST | debit_user_wallet |
| POST | credit_user_wallet |

+ Parameters
    + user_identifier: john124 (string, required) - A mandatory stirng whith which we can uniquelly identify a single user

### Get users wallet [GET]

Retrieves the details for the given wallet, identified by the customer id

+ Request (application/json)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)

    + Attributes(Wallet)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

### Debit/Credit users wallet [POST]

Debit the users wallet for the given ammount

+ Request wit debit (application/json)

    + Attributes(Transaction Request)
        + operation: debit (string, required) - The operation to execute on the wallet

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832


+ Request with credit (application/json)

    + Attributes(Transaction Request)
        + operation: credit (string, required) - The operation to execute on the wallet

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)
    + Attributes(Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

## Debit users wallet [/wallets/{user_identifier}/debit]

| HTTP verb | Grant|
| :--- | :--- |
| POST | debit_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Debit users wallet [POST]

+ Request (application/json)

    + Attributes(Transaction Request)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)
    + Attributes(Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

## Credit users wallet [/wallets/{user_identifier}/credit]

| HTTP verb | Grant|
| :--- | :--- |
| POST | credit_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Credit users wallet [POST]

+ Request (application/json)
    + Attributes(Transaction Response)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832


+ Response 200 (application/json)
    + Attributes (Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

## Begin asyncronous debit [/wallets/{user_identifier}/startdebit]

| HTTP verb | Grant|
| :--- | :--- |
| POST | debit_async_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Debit users wallet [POST]

+ Request (application/json)
    + Attributes(Transaction Response)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 206 (application/json)
    + Attributes(Async Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

## Begin asyncronous creadit [/wallets/{user_identifier}/startcredit]

| HTTP verb | Grant|
| :--- | :--- |
| POST | credit_async_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Credit users wallet [POST]

+ Request (application/json)
    + Attributes(Transaction Response)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 206 (application/json)
    + Attributes(Async Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private


## Storno transaction [/wallets/{user_identifier}/storno]

| HTTP verb | Grant|
| :--- | :--- |
| POST | storno_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Storno transaction [POST]

+ Request (application/json)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

    + Body

            {
                "transaction_id" : "023842poijflafijh8f73z920jfjow",
                "reason" : "Storno by customer",
                "tags" : ["storno", "STR_C", "by customer"]
            }

+ Response 200 (application/json)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

    + Body

            {
                "Successfull" : true,
                "storno_transaction_id" : "023842poijflafijh8f73z920jfjow"
            }

## Cancel an ongoing transaction [/wallets/{user_identifier}/cancel]

| HTTP verb | Grant|
| :--- | :--- |
| POST | debit_async_user_wallet |
| POST | credit_async_user_wallet |

+ parameters
    + user_identifier: john124 (string) : A mandatory stirng whith which we can uniquelly identify a single user

### Cancel transaction [POST]

+ Request (application/json)

    + Attributes (object)
        + transaction_id: 023842poijflafijh8f73z920jfjow (string, required) - The transaction id to cancel
        + reason: Canceled by customer (string, optional) - Optional clarification
        + tags: storno, CAN_C (array, required) - Array of tags to associate with the transactions

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 204 (application/json)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private

## Complete an ongoing transaction [/wallets/{user_identifier}/commit]

| HTTP verb | Grant|
| :--- | :--- |
| POST | debit_async_user_wallet |
| POST | credit_async_user_wallet |

+ parameters
    + user_identifier: john124 (string) - A mandatory stirng whith which we can uniquelly identify a single user

### Complete transaction [POST]

+ Request (application/json)

    + Attributes (object)
        + transaction_id: 023842poijflafijh8f73z920jfjow (string, required) - The transaction id to cancel

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)
    + Attributes (Transaction Response)

    + Header

            Location: wallets/john124
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private


## Get the wallets transaction history [/wallets/{user_identifier}/transactions]

| HTTP verb | Grant|
| :--- | :--- |
| GET | view_wallet_history |

+ parameters
    + user_identifier: john124 (string) - A mandatory stirng whith which we can uniquelly identify a single user


### Get wallet transaction history [GET]

+ Request (application/json)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)
    + Attributes(object)
        + transactions (array[Transaction Detail])

    + Header

            Location: wallets/john124/pockets/euro_pocket
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private


## Get wallets individual pocket details [/wallets/{user_identifier}/pockets/{pocket_identifier}]

| HTTP verb | Grant|
| :--- | :--- |
| GET | view_wallet_pockets |

+ parameters
   + user_identifier: john124 (string, required) - A mandatory stirng whith which we can uniquelly identify a single user
   + pocket_identifier: euro_pocket (string, required) - String uniquelly identifying the pocket for which details should be retrieved


### Get pocket details [GET]

+ Request (application/json)

    + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)
    + Attributes(Pocket Detail)

    + Header

            Location: wallets/john124/pockets/euro_pocket
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private


## Get wallets individual pockets transactions [/wallets/{user_identifier}/pockets/{pocket_identifier}/transactions]

| HTTP verb | Grant|
| :--- | :--- |
| GET | view_wallet_pocket_history |

+ Parameters
   + user_identifier: john124 (string, required) - A mandatory stirng whith which we can uniquelly identify a single user
   + pocket_identifier: euro_pocket (string, required) - String uniquelly identifying the pocket whose history should be retrieved

### Get pocket history [GET]

+ Request (application/json)

   + Header

            AccessToken: ijsefh938ru23p40i20irjdw09d832

+ Response 200 (application/json)

    + Attributes(object)
        + transactions (array[Transaction Detail])

   + Header

            Location: wallets/john124/pockets/euro_pocket/transactions
            Expires: Sun, 08 Nov 2015 21:11:41 +0000
            Last-Modified: Thu, 04 Jun 2015 21:11:41 +0000
            Cache-Control: private
